package com.c11.cartool;

/**
 * Web 远程控制页面生成器。
 *
 * 大厂风格深色主题车控遥控器：
 * - 手机端优先响应式布局
 * - 卡片式分组控制
 * - 实时连接状态 + Toast 反馈
 * - 日志查看 / 一键诊断
 * v0.3.7 安全加固：所有 API fetch 携带 X-Auth-Token
 */
public final class WebPages {

    private WebPages() {}

    public static String getIndexPage(String authToken) {
        String token = (authToken == null) ? "" : authToken;
        // 在 JS 中注入 token，并从 URL ?t=xxx 兼容读取
        return HTML.replace("__AUTH_TOKEN__", token);
    }

    private static final String HTML = "<!DOCTYPE html>"
+ "<html lang='zh-CN'><head>"
+ "<meta charset='UTF-8'>"
+ "<meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no'>"
+ "<meta name='apple-mobile-web-app-capable' content='yes'>"
+ "<meta name='theme-color' content='#0A0E14'>"
+ "<title>C11 车控</title>"
+ "<style>"
+ "*{margin:0;padding:0;box-sizing:border-box;-webkit-tap-highlight-color:transparent}"
+ ":root{--bg:#0A0E14;--card:#151B24;--card2:#1C2430;--border:#252D3A;--fg:#E8ECF1;--fg2:#8B95A5;--fg3:#5A6474;--blue:#3B82F6;--blue2:#2563EB;--green:#10B981;--red:#EF4444;--amber:#F59E0B;--radius:14px;--radius-sm:10px}"
+ "body{background:var(--bg);color:var(--fg);font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC','Noto Sans SC',sans-serif;font-size:15px;line-height:1.5;overflow-x:hidden;padding-bottom:80px}"
+ ".app{max-width:480px;margin:0 auto;padding:0 16px}"
+ ".topbar{position:sticky;top:0;z-index:100;background:rgba(10,14,20,.85);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);padding:12px 16px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--border);margin:0 -16px 16px}"
+ ".topbar .title{font-size:18px;font-weight:700;letter-spacing:-.3px}"
+ ".topbar .title span{color:var(--blue)}"
+ ".conn{display:flex;align-items:center;gap:6px;font-size:13px;color:var(--fg2);background:var(--card);padding:5px 12px;border-radius:20px;border:1px solid var(--border)}"
+ ".dot{width:8px;height:8px;border-radius:50%;background:var(--fg3);transition:all .3s}"
+ ".dot.on{background:var(--green);box-shadow:0 0 8px rgba(16,185,129,.6)}"
+ ".dot.off{background:var(--red);box-shadow:0 0 8px rgba(239,68,68,.4)}"
+ ".vehicle-card{background:linear-gradient(135deg,#1A2332 0%,#0F1620 100%);border:1px solid var(--border);border-radius:var(--radius);padding:20px;margin-bottom:16px;position:relative;overflow:hidden}"
+ ".vehicle-card::before{content:'';position:absolute;top:-40px;right:-40px;width:120px;height:120px;background:radial-gradient(circle,rgba(59,130,246,.12) 0%,transparent 70%);border-radius:50%}"
+ ".vc-row{display:flex;justify-content:space-between;align-items:flex-end;position:relative;z-index:1}"
+ ".vc-item{flex:1}"
+ ".vc-label{font-size:12px;color:var(--fg3);margin-bottom:4px;text-transform:uppercase;letter-spacing:.5px}"
+ ".vc-value{font-size:28px;font-weight:700;letter-spacing:-1px}"
+ ".vc-unit{font-size:14px;font-weight:400;color:var(--fg2);margin-left:2px}"
+ ".vc-sub{font-size:12px;color:var(--fg2);margin-top:2px}"
+ ".group{background:var(--card);border:1px solid var(--border);border-radius:var(--radius);margin-bottom:14px;overflow:hidden}"
+ ".group-header{padding:14px 16px 8px;display:flex;align-items:center;gap:8px}"
+ ".group-icon{font-size:16px}"
+ ".group-title{font-size:13px;font-weight:600;color:var(--fg2);text-transform:uppercase;letter-spacing:.8px}"
+ ".group-body{padding:4px 12px 14px;display:grid;grid-template-columns:repeat(auto-fill,minmax(96px,1fr));gap:8px}"
+ ".group-body.cols-2{grid-template-columns:1fr 1fr}"
+ ".group-body.cols-3{grid-template-columns:repeat(3,1fr)}"
+ ".group-body.cols-4{grid-template-columns:repeat(4,1fr)}"
+ ".ctrl{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;padding:14px 6px;border-radius:var(--radius-sm);background:var(--card2);border:1px solid transparent;cursor:pointer;transition:all .15s;user-select:none;position:relative;overflow:hidden}"
+ ".ctrl:active{transform:scale(.94);background:var(--border)}"
+ ".ctrl.loading{opacity:.5;pointer-events:none}"
+ ".ctrl.success{border-color:var(--green);background:rgba(16,185,129,.1)}"
+ ".ctrl.fail{border-color:var(--red);background:rgba(239,68,68,.1)}"
+ ".ctrl .icon{font-size:22px;line-height:1}"
+ ".ctrl .label{font-size:11px;color:var(--fg2);text-align:center;line-height:1.2}"
+ ".ctrl.primary{background:linear-gradient(135deg,var(--blue) 0%,var(--blue2) 100%);border-color:transparent}"
+ ".ctrl.primary .label{color:rgba(255,255,255,.85)}"
+ ".ctrl.danger{background:linear-gradient(135deg,#DC2626 0%,#B91C1C 100%)}"
+ ".ctrl.danger .label{color:rgba(255,255,255,.85)}"
+ ".ctrl.wide{grid-column:span 2;flex-direction:row;justify-content:center;gap:8px;padding:16px}"
+ ".ctrl.wide .icon{font-size:18px}"
+ ".ctrl.wide .label{font-size:13px;font-weight:500;color:var(--fg)}"
+ ".ctrl.primary.wide .label,.ctrl.danger.wide .label{color:#fff}"
+ ".stepper{display:flex;align-items:center;gap:0;grid-column:span 2;background:var(--card2);border-radius:var(--radius-sm);overflow:hidden}"
+ ".stepper button{flex:1;padding:14px 0;background:none;border:none;color:var(--fg);font-size:20px;cursor:pointer}"
+ ".stepper button:active{background:var(--border)}"
+ ".stepper .val{min-width:64px;text-align:center;font-size:16px;font-weight:600}"
+ ".stepper .val small{font-size:11px;color:var(--fg3);display:block;font-weight:400}"
+ ".bottombar{position:fixed;bottom:0;left:0;right:0;z-index:100;background:rgba(21,27,36,.92);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);border-top:1px solid var(--border);padding:10px 16px;padding-bottom:calc(10px + env(safe-area-inset-bottom))}"
+ ".bottombar .inner{max-width:480px;margin:0 auto;display:flex;gap:10px}"
+ ".bb-btn{flex:1;padding:12px;border-radius:var(--radius-sm);background:var(--card2);border:1px solid var(--border);color:var(--fg);font-size:13px;font-weight:500;cursor:pointer;display:flex;align-items:center;justify-content:center;gap:6px;transition:all .15s}"
+ ".bb-btn:active{transform:scale(.97);background:var(--border)}"
+ ".bb-btn.accent{background:var(--blue);border-color:var(--blue);color:#fff}"
+ ".toast-wrap{position:fixed;top:60px;left:50%;transform:translateX(-50%);z-index:200;display:flex;flex-direction:column;gap:8px;pointer-events:none;width:90%;max-width:400px}"
+ ".toast{padding:12px 18px;border-radius:var(--radius-sm);font-size:14px;font-weight:500;text-align:center;animation:slideDown .3s ease;box-shadow:0 8px 32px rgba(0,0,0,.4)}"
+ ".toast.ok{background:rgba(16,185,129,.95);color:#fff}"
+ ".toast.err{background:rgba(239,68,68,.95);color:#fff}"
+ ".toast.info{background:rgba(59,130,246,.95);color:#fff}"
+ "@keyframes slideDown{from{opacity:0;transform:translateY(-20px)}to{opacity:1;transform:translateY(0)}}"
+ ".modal{position:fixed;inset:0;z-index:300;background:rgba(0,0,0,.7);backdrop-filter:blur(4px);display:none;flex-direction:column}"
+ ".modal.show{display:flex}"
+ ".modal-card{background:var(--bg);margin:0;border-radius:20px 20px 0 0;height:90vh;display:flex;flex-direction:column;border-top:1px solid var(--border)}"
+ ".modal-header{padding:16px 20px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--border)}"
+ ".modal-title{font-size:16px;font-weight:600}"
+ ".modal-close{width:32px;height:32px;border-radius:50%;background:var(--card2);border:none;color:var(--fg2);font-size:16px;cursor:pointer;display:flex;align-items:center;justify-content:center}"
+ ".modal-body{flex:1;overflow-y:auto;padding:12px 16px}"
+ ".log-line{font-family:'SF Mono',Menlo,Consolas,monospace;font-size:11px;line-height:1.6;color:var(--fg2);padding:1px 0;word-break:break-all;white-space:pre-wrap}"
+ ".log-line.err{color:var(--red)}"
+ ".log-line.ok{color:var(--green)}"
+ ".log-line.warn{color:var(--amber)}"
+ ".modal-footer{padding:12px 16px;border-top:1px solid var(--border);display:flex;gap:10px;padding-bottom:calc(12px + env(safe-area-inset-bottom))}"
+ ".modal-footer button{flex:1;padding:12px;border-radius:var(--radius-sm);border:1px solid var(--border);background:var(--card2);color:var(--fg);font-size:13px;cursor:pointer}"
+ ".modal-footer button.primary{background:var(--blue);border-color:var(--blue);color:#fff}"
+ ".spinner{width:16px;height:16px;border:2px solid rgba(255,255,255,.2);border-top-color:#fff;border-radius:50%;animation:spin .6s linear infinite;display:inline-block}"
+ "@keyframes spin{to{transform:rotate(360deg)}}"
+ ".perm-tag{font-size:11px;padding:2px 8px;border-radius:10px;font-weight:500}"
+ ".perm-shell{background:rgba(16,185,129,.15);color:var(--green)}"
+ ".perm-normal{background:rgba(239,68,68,.15);color:var(--red)}"
+ ".perm-unknown{background:rgba(245,158,11,.15);color:var(--amber)}"
+ ".srv-info{font-size:11px;color:var(--dim);padding:0 16px 8px;text-align:center}"
+ "</style></head><body>"
+ "<div class='topbar'><div class='title'>C11 <span>车控</span></div>"
+ "<div class='conn'><div class='dot' id='connDot'></div><span id='connText'>连接中...</span></div></div>"
+ "<div id='serverInfo' class='srv-info'>获取服务端信息...</div>"
+ "<div class='app'>"
+ "<div class='vehicle-card'><div class='vc-row'>"
+ "<div class='vc-item'><div class='vc-label'>电量</div><div class='vc-value' id='vBattery'>--<span class='vc-unit'>%</span></div><div class='vc-sub' id='vRange'>续航 -- km</div></div>"
+ "<div class='vc-item' style='text-align:right'><div class='vc-label'>车速</div><div class='vc-value' id='vSpeed'>--<span class='vc-unit'>km/h</span></div><div class='vc-sub' id='vGear'>档位 --</div></div>"
+ "</div></div>"
+ "<div class='group'><div class='group-header'><span class='group-icon'>🔐</span><span class='group-title'>车门 / 后备箱</span></div>"
+ "<div class='group-body cols-3'>"
+ "<div class='ctrl primary' onclick='cmd(\"lockCar\",this)'><span class='icon'>🔒</span><span class='label'>锁车</span></div>"
+ "<div class='ctrl' onclick='cmd(\"unlockCar\",this)'><span class='icon'>🔓</span><span class='label'>解锁</span></div>"
+ "<div class='ctrl' onclick='cmd(\"openTrunk\",this)'><span class='icon'>📤</span><span class='label'>后备箱</span></div>"
+ "</div></div>"
+ "<div class='group'><div class='group-header'><span class='group-icon'>💡</span><span class='group-title'>灯光控制</span></div>"
+ "<div class='group-body cols-3'>"
+ "<div class='ctrl' onclick='cmd(\"lowBeamOn\",this)'><span class='icon'>💡</span><span class='label'>近光开</span></div>"
+ "<div class='ctrl' onclick='cmd(\"lowBeamOff\",this)'><span class='icon'>🌑</span><span class='label'>近光关</span></div>"
+ "<div class='ctrl' onclick='cmd(\"fogLightOn\",this)'><span class='icon'>🌫️</span><span class='label'>雾灯开</span></div>"
+ "<div class='ctrl' onclick='cmd(\"fogLightOff\",this)'><span class='icon'>🌤️</span><span class='label'>雾灯关</span></div>"
+ "<div class='ctrl' onclick='cmd(\"positionLightOn\",this)'><span class='icon'>🔦</span><span class='label'>示廓开</span></div>"
+ "<div class='ctrl' onclick='cmd(\"positionLightOff\",this)'><span class='icon'>🔦</span><span class='label'>示廓关</span></div>"
+ "</div></div>"
+ "<div class='group'><div class='group-header'><span class='group-icon'>❄️</span><span class='group-title'>空调控制</span></div>"
+ "<div class='group-body'>"
+ "<div class='ctrl primary wide' onclick='cmd(\"acMaxOn\",this)'><span class='icon'>🧊</span><span class='label'>最大制冷 ON</span></div>"
+ "<div class='ctrl wide' onclick='cmd(\"acMaxOff\",this)'><span class='icon'>🔵</span><span class='label'>最大制冷 OFF</span></div>"
+ "<div class='ctrl' onclick='cmd(\"acOn\",this)'><span class='icon'>❄️</span><span class='label'>空调开</span></div>"
+ "<div class='ctrl' onclick='cmd(\"acOff\",this)'><span class='icon'>🚫</span><span class='label'>空调关</span></div>"
+ "<div class='ctrl' onclick='cmd(\"frontDefrost\",this)'><span class='icon'>🌬️</span><span class='label'>前除霜</span></div>"
+ "<div class='ctrl' onclick='cmd(\"rearDefrost\",this)'><span class='icon'>🌬️</span><span class='label'>后除霜</span></div>"
+ "<div class='stepper'><button onclick='cmd(\"acTempDown\",this)'>−</button><div class='val' id='acTemp'>24°<small>温度</small></div><button onclick='cmd(\"acTempUp\",this)'>+</button></div>"
+ "<div class='stepper'><button onclick='cmd(\"acFanDown\",this)'>−</button><div class='val' id='acFan'>3<small>风量</small></div><button onclick='cmd(\"acFanUp\",this)'>+</button></div>"
+ "</div></div>"
+ "<div class='group'><div class='group-header'><span class='group-icon'>🪟</span><span class='group-title'>车窗控制</span></div>"
+ "<div class='group-body cols-4'>"
+ "<div class='ctrl' onclick='cmd(\"windowFLUp\",this)'><span class='icon'>⬆️</span><span class='label'>主驾升</span></div>"
+ "<div class='ctrl' onclick='cmd(\"windowFLDown\",this)'><span class='icon'>⬇️</span><span class='label'>主驾降</span></div>"
+ "<div class='ctrl' onclick='cmd(\"windowFRUp\",this)'><span class='icon'>⬆️</span><span class='label'>副驾升</span></div>"
+ "<div class='ctrl' onclick='cmd(\"windowFRDown\",this)'><span class='icon'>⬇️</span><span class='label'>副驾降</span></div>"
+ "<div class='ctrl' onclick='cmd(\"windowRLUp\",this)'><span class='icon'>⬆️</span><span class='label'>左后升</span></div>"
+ "<div class='ctrl' onclick='cmd(\"windowRLDown\",this)'><span class='icon'>⬇️</span><span class='label'>左后降</span></div>"
+ "<div class='ctrl' onclick='cmd(\"windowRRUp\",this)'><span class='icon'>⬆️</span><span class='label'>右后升</span></div>"
+ "<div class='ctrl' onclick='cmd(\"windowRRDown\",this)'><span class='icon'>⬇️</span><span class='label'>右后降</span></div>"
+ "</div></div>"
+ "<div class='group'><div class='group-header'><span class='group-icon'>⚙️</span><span class='group-title'>其他控制</span></div>"
+ "<div class='group-body cols-3'>"
+ "<div class='ctrl' onclick='cmd(\"leftChildLock\",this)'><span class='icon'>👶</span><span class='label'>左儿童锁</span></div>"
+ "<div class='ctrl' onclick='cmd(\"rightChildLock\",this)'><span class='icon'>👶</span><span class='label'>右儿童锁</span></div>"
+ "<div class='ctrl' onclick='cmd(\"open360\",this)'><span class='icon'>🅿️</span><span class='label'>360全景</span></div>"
+ "</div></div>"
+ "</div>" + "<div class='bottombar'><div class='inner'>"
+ "<button class='bb-btn' onclick='openLogs()'>📋 日志</button>"
+ "<button class='bb-btn' onclick='runDiag()'>🔍 诊断</button>"
+ "<button class='bb-btn accent' onclick='refreshStatus()'>🔄 刷新</button>"
+ "</div></div>"
+ "<div class='toast-wrap' id='toastWrap'></div>"
+ "<div class='modal' id='logModal'><div class='modal-card'>"
+ "<div class='modal-header'><span class='modal-title'>系统日志</span><button class='modal-close' onclick='closeLogs()'>✕</button></div>"
+ "<div class='modal-body' id='logContent'><div class='log-line'>加载中...</div></div>"
+ "<div class='modal-footer'><button onclick='loadLogs()'>刷新日志</button><button class='primary' onclick='closeLogs()'>关闭</button></div>"
+ "</div></div>"
+ "<script>"
+ "var busy=false;"
+ "function toast(msg,type){"
+ "var w=document.getElementById('toastWrap');"
+ "var t=document.createElement('div');"
+ "t.className='toast '+(type||'info');t.textContent=msg;w.appendChild(t);"
+ "setTimeout(function(){t.style.opacity='0';t.style.transition='opacity .3s';setTimeout(function(){t.remove()},300)},2500);"
+ "}"
+ "var AUTH_TOKEN='__AUTH_TOKEN__';"
+ "function authHeaders(){return {'Content-Type':'application/json','X-Auth-Token':AUTH_TOKEN};}"
+ "function cmd(action,btn){"
+ "if(busy){toast('请稍候...','info');return;}"
+ "busy=true;"
+ "if(btn){btn.classList.add('loading');var orig=btn.innerHTML;btn.innerHTML='<span class=spinner></span>';}"
+ "fetch('/api/control',{method:'POST',headers:authHeaders(),body:JSON.stringify({action:action})})"
+ ".then(function(r){return r.json()})"
+ ".then(function(d){"
+ "busy=false;"
+ "if(btn){btn.classList.remove('loading');btn.innerHTML=orig;"
+ "if(d.success){btn.classList.add('success');setTimeout(function(){btn.classList.remove('success')},1500);}"
+ "else{btn.classList.add('fail');setTimeout(function(){btn.classList.remove('fail')},1500);}}"
+ "if(d.success){toast('操作成功','ok');}else{toast('失败: '+(d.error||'未知错误'),'err');}"
+ "}).catch(function(e){"
+ "busy=false;"
+ "if(btn){btn.classList.remove('loading');btn.innerHTML=orig;btn.classList.add('fail');setTimeout(function(){btn.classList.remove('fail')},1500);}"
+ "toast('网络错误: '+e.message,'err');"
+ "});"
+ "}"
+ "function refreshStatus(){"
+ "fetch('/api/info').then(function(r){return r.json()}).then(function(d){"
+ "var dot=document.getElementById('connDot'),txt=document.getElementById('connText');"
+ "if(d.adbConnected){dot.className='dot on';txt.textContent=d.permission||('ADB uid='+d.uid);}"
+ "else{dot.className='dot off';txt.textContent='未连接ADB';}"
+ "var si=document.getElementById('serverInfo');"
+ "if(si){var iptxt='';if(d.ips&&d.ips.length){for(var i=0;i<d.ips.length;i++){iptxt+=(i>0?' / ':'')+d.ips[i];}}"
+ "si.textContent='服务端: '+iptxt+' | v'+d.version+(d.running?'':' (服务已停止)');}"
+ "}).catch(function(){document.getElementById('connDot').className='dot off';document.getElementById('connText').textContent='服务器离线';});"
+ "fetch('/api/status').then(function(r){return r.json()}).then(function(d){"
+ "if(d.data){"
+ "if(d.data.battery)document.getElementById('vBattery').innerHTML=d.data.battery+'<span class=vc-unit>%</span>';"
+ "if(d.data.range)document.getElementById('vRange').textContent='续航 '+d.data.range+' km';"
+ "if(d.data.speed)document.getElementById('vSpeed').innerHTML=d.data.speed+'<span class=vc-unit>km/h</span>';"
+ "if(d.data.gear)document.getElementById('vGear').textContent='档位 '+d.data.gear;"
+ "}"
+ "}).catch(function(){});"
+ "}"
+ "function openLogs(){document.getElementById('logModal').classList.add('show');loadLogs();}"
+ "function closeLogs(){document.getElementById('logModal').classList.remove('show');}"
+ "function loadLogs(){"
+ "var el=document.getElementById('logContent');el.innerHTML='<div class=log-line>加载中...</div>';"
+ "fetch('/api/logs').then(function(r){return r.json()}).then(function(d){"
+ "if(!d.logs){el.innerHTML='<div class=log-line>暂无日志</div>';return;}"
+ "var lines=d.logs.split('\\n');"
+ "var html='';"
+ "for(var i=0;i<lines.length;i++){var l=lines[i];var cls='';if(l.indexOf('失败')>=0||l.indexOf('错误')>=0||l.indexOf('error')>=0)cls='err';else if(l.indexOf('成功')>=0||l.indexOf('OK')>=0)cls='ok';else if(l.indexOf('警告')>=0||l.indexOf('warn')>=0)cls='warn';html+='<div class=log-line '+cls+'>'+escapeHtml(l)+'</div>';}"
+ "el.innerHTML=html;el.scrollTop=el.scrollHeight;"
+ "}).catch(function(e){el.innerHTML='<div class=log-line err>加载失败: '+e.message+'</div>';});"
+ "}"
+ "function runDiag(){"
+ "toast('诊断开始，请稍候...','info');"
+ "fetch('/api/diagnostic').then(function(r){return r.json()}).then(function(d){"
+ "if(d.report){openLogs();setTimeout(function(){document.getElementById('logContent').innerHTML='<div class=log-line>'+escapeHtml(d.report).replace(/\\n/g,'</div><div class=log-line>')+'</div>';},500);toast('诊断完成','ok');}"
+ "else{toast('诊断失败','err');}"
+ "}).catch(function(e){toast('诊断错误: '+e.message,'err');});"
+ "}"
+ "function escapeHtml(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML;}"
+ "if(!AUTH_TOKEN){var m=location.search.match(/[?&]t=([^&]+)/);if(m)AUTH_TOKEN=decodeURIComponent(m[1]);}"
+ "refreshStatus();"
+ "setInterval(refreshStatus,5000);"
+ "</script></body></html>";
}
