plugins {
    id 'com.android.application'
}

android {
    compileSdk 28
    namespace 'com.c11.cartool'

    defaultConfig {
        applicationId "com.c11.cartool"
        minSdk 28
        targetSdk 28
        versionCode 13
        versionName "0.3.7"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
        }
        debug {
            minifyEnabled true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    // 不使用 AndroidX (兼容车机 Android 9)
    useLibrary 'android.test.base'
    useLibrary 'android.test.mock'
}

dependencies {
    // 无外部依赖，纯 Android SDK
}
